# Site settings
title: William Mora
email: william.r.mora@gmail.com
description: "Software development (mostly). Random tech, tips, thoughts, etc."
baseurl: ""
url: "https://williammora.com"
domain: "williammora.com"
twitter_username: _williammora
github_username: wmora
isso_domain:
copyright_start_year: 2010

# Build settings
source: .
permalink: /:title

excerpt_separator: "<!--more-->"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      share: true # Sharing enabled
      display_ad: true
      display_donate: false

plugins:
  - jekyll-redirect-from
