# Site settings
title: William Mora
email: william.r.mora@gmail.com
description: "Software development (mostly). Random tech, tips, thoughts, etc."
baseurl: ""
url: "http://williammora.com"
twitter_username: _williammora
github_username: wmora
disqus_username: williammora
isso_domain: 
ga_tracking_id: UA-39417110-1

# Build settings
markdown: redcarpet
source: .
permalink: /:title

excerpt_separator: "<!--more-->"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      share: true # Sharing enabled
      display_ad: true
      display_donate: true

gems:
  - jekyll-redirect-from